production:
  loglevel: info
  #logfile: './logs/pro-logs.log'

development:
  # loglevel: validation
  loglevel: validationWarning
  #logfile: './dev-logs.log' #if dir is specified before file: EXCEPTION